name: numeric_steeper
description: "Numeric steeper widget"
version: 0.1.0
homepage: https://github.com/VladimirFelix/NumericSteeper
repository: https://github.com/VladimirFelix/NumericSteeper
issue_tracker: https://github.com/VladimirFelix/NumericSteeper/issues
topics:
  - stepper
  - counter
  - widget
  - numeric
  - customizable

environment:
  sdk: ">=3.3.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.


# No assets or fonts needed yet